version: '3'
services:
  console:
    image: ekoopensource/octopusx-console
    ports:
      - "5000:8080"
    env_file:
      - .env
  access:
    image: ekoopensource/octopusx-access:v1.01
    env_file:
      - .env
    ports:
      - "5001:5000"