annotations:
  category: Infrastructure
apiVersion: v1
appVersion: 5.0.2
description: phpMyAdmin is an mysql administration frontend
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/phpmyadmin
icon: https://bitnami.com/assets/stacks/phpmyadmin/img/phpmyadmin-stack-220x234.png
keywords:
- mariadb
- mysql
- phpmyadmin
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: phpmyadmin
sources:
- https://github.com/bitnami/bitnami-docker-phpmyadmin
- https://www.phpmyadmin.net/
version: 6.5.2
